-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Boletins"
(
    id integer NOT NULL,
    path character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    usuario_id integer,
    quantidade integer,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Cursos"
(
    id integer NOT NULL,
    designacao character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."SequelizeMeta"
(
    name character varying(255) NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE public."Usuarios"
(
    id integer NOT NULL,
    nome_completo character varying(255),
    "isAdmin" boolean NOT NULL,
    email character varying NOT NULL,
    activo boolean NOT NULL,
    curso_id integer,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    senha_hash character varying,
    PRIMARY KEY (id)
);

ALTER TABLE public."Boletins"
    ADD FOREIGN KEY (usuario_id)
    REFERENCES public."Usuarios" (id)
    NOT VALID;

END;